### ISSUE TITLE
Abrechnungen Excel Export

### ISSUE THREAD

**Issue by Pictarin** [TheDonDope/kindergarten#21]
- Die Verkäufernummern werden nicht sortiert in Excel geschrieben (selbe Problem besteht auch bei der 
  Erfassung) Bsp.:
  Erfasse neuen Verkäufer -> Vendornummer -> 5 -> 4 -> 27 -> 1 
  Anzeige hierfür ist dann: 5, 4, 27, 1

**Comment by mjaeger13** [comment]
Wenn wir das umsetzen, dann bitte konsistent in der ganzen Anwendung umsetzen! Sprich die Verkäufernummern müssen überall wo sie angezeigt werden dann absteigend sortiert angezeigt werden.

**Comment by TheDonDope** [comment]
Betroffene Codestelle: https://github.com/clear-group-ausbildung/kindergarten/blob/develop/src/main/java/de/clearit/kindergarten/domain/VendorNumberService.java#L91

Die Liste wird momentan unsortiert zurückgegeben, hier muss vor der Rückgabe noch sortiert werden.

**Comment by Pictarin** [comment]
erledigt - wird in der Anwendung sortiert dadurch auch korrekte Ausgabe
