### ISSUE TITLE
Verkaufserfassung

### ISSUE THREAD

**Issue by Pictarin** [TheDonDope/kindergarten#26]
- [x] wenn ein neuer Artikel erfasst werden soll und bei Artikelpreis der preis mit einem "-" erfasst wird 
  (1-1) erkennt er das als Eintrag und schreibt es "unsichtbar" in die Tabelle. Sobald ein korrekter Eintrag 
  getätigt wird werden alle "unsichtbaren" hinzugefügten mit dem neuen ersetzt -> es passiert das dann 
  z.B.: 5 mal der selbe Artikel mit selben Preis erfasst wird

**Comment by TheDonDope** [comment]
Fixed by https://github.com/clear-group-ausbildung/kindergarten/commit/aedaeada57e33856375af98824f2ff599ae5000e
