### ISSUE TITLE
Verkäufernummererfassung Keine überprüfung ob in der "erfassungsTabelle"

### ISSUE THREAD

**Issue by Pictarin** [TheDonDope/kindergarten#36]
Anlegen eines neuen Verkäufers findet keine Überprüfung statt ob in der Tabelle (unten drunter) die Nummer bereits eingetragen ist

**Comment by TheDonDope** [comment]
Fixed on `develop` by c57924976f45ba0cb14de9a87edb1a0385dc4c55
