### ISSUE TITLE
Vendornumber delete and cancel

### ISSUE THREAD

**Issue by Pictarin** [TheDonDope/kindergarten#39]
Vendor bearbeiten -> Vendornumber löschen -> Abbrechen -> Nummer weg 
Nach neustart Nummer wieder da

Frontend anpassungen notwendig

**Comment by Pictarin** [comment]
performCancel() in VendorEditorModel.java abgeändert

**Comment by TheDonDope** [comment]
Behebung auf `develop` via faca8d4662ec339338d1ba917954be5508ebfec1
