### ISSUE TITLE
Vendornumber delete and add same number again after click ok

### ISSUE THREAD

**Issue by Pictarin** [TheDonDope/kindergarten#40]
Wenn man eine Verkäufernummer löscht dann auf Ok und dann wieder auf bearbeiten -> selbe Nummer eingeben, kann diese Nummer nicht mehr diesem Verkäufer zugeteilt werden

**Comment by TheDonDope** [comment]
Habe es auf dem develop Stand (638c0202ca4fcd371e731ade7b3eae7959ad5645) nachgetestet, funktioniert!

**Comment by TheDonDope** [comment]
Behebung auf `develop` in Zusammenhang mit #39 via faca8d4662ec339338d1ba917954be5508ebfec1
