### ISSUE TITLE
Fehlermeldungstexte enthalten Property Namen

### ISSUE THREAD

**Issue by TheDonDope** [TheDonDope/kindergarten#42]
IST: In Validierungsdialogen werden die Propertynamen (z.B.: `.lastName Geben Sie einen Nachnamen ein`) am Beginn der jeweiligen Meldung ausgegeben.

SOLL: Die Propertynamen sollen nicht mit ausgegeben werden

**Comment by TheDonDope** [comment]
Betroffene Codestelle: https://github.com/clear-group-ausbildung/kindergarten/blob/develop/src/main/java/de/clearit/kindergarten/application/Dialogs.java#L50

Hier wird momentan einfach vom `ValidationResult` die Methode `getMessagesText()` aufgerufen, die hat diese liefert diese komische .PROPERTYNAME <Text> Formatierung. Man muss mal schauen was man aus dem `ValidationResult` herausziehen kann um die Auflistung im StringBuilder selbst zusammenzubauen (dort ist auch einkommentierter Code, wie so etwas ungefähr gehen könnte)

**Comment by Pictarin** [comment]
Von Kenan erledigt - nicht gepusht

**Comment by Regulant** [comment]
Ist jetzt auf develop gepusht.
